Fix decorator, closes #6.
Address the following Error caused by Flask-JWT-Extended due to breaking changes:
`TypeError: wrapper() got an unexpected keyword argument 'username'`